[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

# Next.js SSR/ISR on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"